version: '2.4'
services:
  db:
    container_name: project-db
    image: mariadb
    platform: linux/amd64
    env_file:
      - pro.env
    networks:
      - app_net
  pma:
    container_name: 'project-pma'
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
    - "8000:80"
    links:
      - db:mysql
    env_file:
      - pro.env
    networks:
      - app_net
  app:
    container_name: project-app
    platform: linux/amd64
    build: .
    ports:
    - "80:8080"
    links:
      - db:mysql
    env_file:
      - pro.env
    networks:
      - app_net

networks:
  app_net:
